# Experimental Settings
fps: 50        # camera frame rate (units: frames/sec)
input_data_path: "data/ant_field_round1"
result_path: "results/test"

# Signals
bp_center: 2
bp_scale: [1, 2]
bp_rotate: 1
angles:
  # RIGHT ANTENNAE
  #- {"a": 6, "b": 5, "c": 4} # tip
  - {"a": 7, "b": 6, "c": 5}
  # RIGHT FRONT-LEG
  - {"a": 2, "b": 9, "c": 8}
  # RIGHT MID-LEG
  # - {"a": 2, "b": 12, "c": 11}
  - {"a": 1, "b": 2, "c": 11}
  # RIGHT BACK-LEG
  # - {"a": 2, "b": 15, "c": 14}
  # - {"a": 16, "b": 15, "c": 14}
  - {"a": 3, "b": 15, "c": 14}
  
  # LEFT ANTENNAE
  #- {"a": 19, "b": 18, "c": 17} # tip
  - {"a": 20, "b": 19, "c": 18}
  # LEFT FRONT-LEG
  - {"a": 2, "b": 22, "c": 21}
  # LEFT MID-LEG
  # - {"a": 2, "b": 25, "c": 24}
  - {"a": 1, "b": 2, "c": 24}
  # LEFT BACK-LEG
  # - {"a": 2, "b": 28, "c": 27}
  - {"a": 3, "b": 28, "c": 27}
angle_labels:
  - Right Antennae 
  - Right Front-Leg
  - Right Mid-Leg
  - Right Back-Leg
  - Left Antennae 
  - Left Front-Leg
  - Left Mid-Leg
  - Left Back-Leg

# Morlet Wavelet Transformation
w: 5
f_bin: 20       # number of frequency bin

# UMAP
n_components: 2
n_neighbors: 150
n_epochs: 15000
min_dist: 0.01
negative_sample_rate: 5
init: "spectral"
repulsion_strength: 2

# Clustering (HDBSCAN, GMM)

# Figures
save_video_path: "videos/round2_legs_antennae"
num_sample_videos: 3
max_video_length: 80

# Save
save_bodypoints: True
save_scaled_bodypoints: True
save_rotated_bodypoints: True
save_body_orientation_angles: True
save_angles: True
save_powers: True
save_embeddings: True
save_clusters: True