# Experimental Settings
fps: 50          # camera frame rate (units: frames/sec)
camera_scale: 60 # pixel/cm
input_data_path: "data/ant_field_round3"
result_path: "results/round3_antennae"

# Signals
bp_center: 2
bp_scale: [1, 2]
bp_rotate: 1
angles:
  # RIGHT ANTENNAE
  - {"a": 0, "b": 6, "c": 5}
  # RIGHT ANTENNAE 2
  - {"a": 1, "b": 0, "c": 6}
  
  # LEFT ANTENNAE
  - {"a": 0, "b": 19, "c": 18}
  # LEFT ANTENNAE 2
  - {"a": 1, "b": 0, "c": 19}
angle_labels:
  - (R) Antennae
  - (R) Antennae 2 
  - (L) Antennae 
  - (L) Antennae 2

# Morlet Wavelet Transformation
w: 5
f_bin: 20       # number of frequency bin

# UMAP
n_components: 2
n_neighbors: 40
n_epochs: 5000
min_dist: 0.01
spread: 1.0 # 3.0
negative_sample_rate: 5
init: "spectral"
repulsion_strength: 1.0 # 10

# Clustering (HDBSCAN, GMM)

# Figures
save_video_path: "videos/round2_legs_antennae"
num_sample_videos: 3
max_video_length: 80

# Save
save_bodypoints: False
save_scaled_bodypoints: False
save_rotated_bodypoints: False
save_body_orientation_angles: False
save_angles: False
save_powers: False
save_embeddings: False
save_clusters: False
