### Experimental Settings ###
fps: 7          # camera frame rate (units: frames/sec)
input_data_path: "data/Mostafizur_Dong"
result_path: "results/Mostafizur_Dong"
GPU_project_path: "/rapids/notebooks/host"
### Skeleton ###
skeleton: [
    [0,1],[0,2],[1,2],[6,7],
    [6,8],[8,12],[12,10],[10,11],[11,7]]
skeleton_color: [
    'tab:blue','tab:blue','tab:blue','tab:blue',
    'tab:blue','tab:blue','tab:blue','tab:blue','tab:blue']
skeleton_fill: []

likelihood_thresh: 0.98
marker_thresh: 1
bad_fr_pad: 50

### Signals ###
bp_center: 6
bp_scale: [6,10]
bp_rotate: 10
scale: 121

### Postural Features ###
# Marker Position
include_marker_postural: False
include_marker_kinematic: False
markers: [0,1,3, 5,6,7, 8,9, 11,12, 14,15, 18,19,20, 21,22, 24,25, 27,28]
marker_kinematic_pca_components: 170
marker_labels: [head, thorax, abdomen, 
(R) Antennae Tip, (R) Antennae Mid, (R) Antennae Base,
(R) FL Tip, (R) FL Mid, (R) ML Tip, (R) ML Mid, (R) HL Tip, (R) HL Mid,
(L) Antennae Tip, (L) Antennae Mid, (L) Antennae Base,
(L) FL Tip, (L) FL Mid, (L) ML Tip, (L) ML Mid, (L) HL Tip, (L) HL Mid]

# Joint Angle
include_angle_postural: False
include_angle_kinematic: False
angle_kinematic_pca_components: 70
angles:
  # HEAD
  - {"a": 0, "b": 6, "c": 10, "method": 1}
  # SNOUT
  - {"a": 1, "b": 0, "c": 2, "method": 1}
  # TOP BODY
  - {"a": 7, "b": 6, "c": 8, "method": 1}
  # BOTTOM BODY
  - {"a": 12, "b": 10, "c": 11, "method": 1}

angle_labels:
  - Head
  - Snout
  - Top Body
  - Bottom Body

# Limb Length
include_limb_postural: False
include_limb_kinematic: False
limb_kinematic_pca_components: 40
limbs:
  - [0,6]
  - [6,10]
limb_labels:
  - Head Length
  - Body Length

limb_threshold:
  - 15
  - 25

include_all_postural: True
include_all_kinematic: True
include_all_features: True

# Morlet Wavelet Transformation
w: 5
f_bin: 20       # number of frequency bin
f_min: 0.5

# Kinematic & Postural Influence
postural_weight: 4 # try 1.5, 2, 2.5, 3
kinematic_weight: 1

# UMAP
n_components: 2
n_neighbors: 40
n_epochs: 10000 
min_dist: 0.001
spread: 1.0 # 3.0
negative_sample_rate: 5
init: "spectral"
repulsion_strength: 3.0 # 10

# Clustering (HDBSCAN, GMM)

# Figures
save_video_path: "videos/Mostafizur_Dong"
num_sample_videos: 3
max_video_length: 80

# Save
save_bodypoints: True
save_scaled_bodypoints: True
save_body_orientation_angles: False
save_rotated_bodypoints: True
save_embeddings: True
save_clusters: False
